---
deployment:
  tasks:
    - export FRONTEND=/home/electrop/public_html/pos.electropointlugbeabuja.com/
    - export BACKEND=/home/electrop/electropoint_backend/
    - /bin/cp -a frontend/dist/* 
    - /bin/cp -a backend/* 
